AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cessao-fundo-csv-to-database

  Application responsible for reading a Cessao Fundo csv and inserting data into database

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  CSVToDatabaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: application.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CessaoFundoCSVToDatabase:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cessao-fundo-csv-to-database
            Method: post
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CessaoFundoCSVToDatabaseApi:
    Description: "API endpoint URL for importing a standard 'cessao_fundo' csv file to database."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cessao-fundo-csv-to-database/"
  CessaoFundoCSVToDatabaseFunction:
    Description: "CessaoFundo CSV To Database Function ARN"
    Value: !GetAtt CSVToDatabaseFunction.Arn
  CessaoFundoCSVToDatabaseFunctionIamRole:
    Description: "Implicit IAM Role created for CessaoFundo CSV To Database"
    Value: !GetAtt CSVToDatabaseFunction.Arn
